### ISSUE TITLE
Add support for `aria-description` attribute

### ISSUE THREAD

**Issue by micmcg** [jsx-eslint/eslint-plugin-jsx-a11y#699]
https://github.com/w3c/aria/pull/1137

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Annotations

This attribute is supported by at least VoiceOver in my testing. Can you please add it to the list of supported props for the `aria-props` rule? I've opened https://github.com/A11yance/aria-query/issues/57 in aria-query request support.

Thanks

**Comment by jessebeach** [comment]
Fixed in v6.3.x

**Comment by DustinBrett** [comment]
Seems like this still isn't supported in my testing. `aria-description` is 1.3 spec and https://github.com/A11yance/aria-query is on 1.2 where the keys come from. Anyone get this working?

**Comment by gabibianconi** [comment]
It is not working in v6.5.1.

![image](https://user-images.githubusercontent.com/25694348/170112568-a9bca28d-2455-4dd2-8d06-6ff19b41e2b4.png)
